// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flconfig.proto

#include "flconfig.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace flremoting {
namespace protocol {
PROTOBUF_CONSTEXPR StartRemoteMessage::StartRemoteMessage(
    ::_pbi::ConstantInitialized)
  : userpath_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , previewhwnd_(0u){}
struct StartRemoteMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StartRemoteMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StartRemoteMessageDefaultTypeInternal() {}
  union {
    StartRemoteMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StartRemoteMessageDefaultTypeInternal _StartRemoteMessage_default_instance_;
}  // namespace protocol
}  // namespace flremoting
namespace flremoting {
namespace protocol {

// ===================================================================

class StartRemoteMessage::_Internal {
 public:
  using HasBits = decltype(std::declval<StartRemoteMessage>()._has_bits_);
  static void set_has_userpath(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_previewhwnd(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

StartRemoteMessage::StartRemoteMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:flremoting.protocol.StartRemoteMessage)
}
StartRemoteMessage::StartRemoteMessage(const StartRemoteMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  userpath_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    userpath_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_userpath()) {
    userpath_.Set(from._internal_userpath(), 
      GetArenaForAllocation());
  }
  previewhwnd_ = from.previewhwnd_;
  // @@protoc_insertion_point(copy_constructor:flremoting.protocol.StartRemoteMessage)
}

inline void StartRemoteMessage::SharedCtor() {
userpath_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  userpath_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
previewhwnd_ = 0u;
}

StartRemoteMessage::~StartRemoteMessage() {
  // @@protoc_insertion_point(destructor:flremoting.protocol.StartRemoteMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StartRemoteMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  userpath_.Destroy();
}

void StartRemoteMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void StartRemoteMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:flremoting.protocol.StartRemoteMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    userpath_.ClearNonDefaultToEmpty();
  }
  previewhwnd_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* StartRemoteMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string userpath = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_userpath();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 previewhwnd = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_previewhwnd(&has_bits);
          previewhwnd_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StartRemoteMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:flremoting.protocol.StartRemoteMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string userpath = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_userpath(), target);
  }

  // optional uint32 previewhwnd = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_previewhwnd(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flremoting.protocol.StartRemoteMessage)
  return target;
}

size_t StartRemoteMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flremoting.protocol.StartRemoteMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string userpath = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_userpath());
    }

    // optional uint32 previewhwnd = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_previewhwnd());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StartRemoteMessage::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const StartRemoteMessage*>(
      &from));
}

void StartRemoteMessage::MergeFrom(const StartRemoteMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:flremoting.protocol.StartRemoteMessage)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_userpath(from._internal_userpath());
    }
    if (cached_has_bits & 0x00000002u) {
      previewhwnd_ = from.previewhwnd_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void StartRemoteMessage::CopyFrom(const StartRemoteMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flremoting.protocol.StartRemoteMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StartRemoteMessage::IsInitialized() const {
  return true;
}

void StartRemoteMessage::InternalSwap(StartRemoteMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &userpath_, lhs_arena,
      &other->userpath_, rhs_arena
  );
  swap(previewhwnd_, other->previewhwnd_);
}

std::string StartRemoteMessage::GetTypeName() const {
  return "flremoting.protocol.StartRemoteMessage";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace flremoting
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::flremoting::protocol::StartRemoteMessage*
Arena::CreateMaybeMessage< ::flremoting::protocol::StartRemoteMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::flremoting::protocol::StartRemoteMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
