// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flconfig.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_flconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_flconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_flconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_flconfig_2eproto {
  static const uint32_t offsets[];
};
namespace flremoting {
namespace protocol {
class StartRemoteMessage;
struct StartRemoteMessageDefaultTypeInternal;
extern StartRemoteMessageDefaultTypeInternal _StartRemoteMessage_default_instance_;
}  // namespace protocol
}  // namespace flremoting
PROTOBUF_NAMESPACE_OPEN
template<> ::flremoting::protocol::StartRemoteMessage* Arena::CreateMaybeMessage<::flremoting::protocol::StartRemoteMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace flremoting {
namespace protocol {

// ===================================================================

class StartRemoteMessage final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:flremoting.protocol.StartRemoteMessage) */ {
 public:
  inline StartRemoteMessage() : StartRemoteMessage(nullptr) {}
  ~StartRemoteMessage() override;
  explicit PROTOBUF_CONSTEXPR StartRemoteMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StartRemoteMessage(const StartRemoteMessage& from);
  StartRemoteMessage(StartRemoteMessage&& from) noexcept
    : StartRemoteMessage() {
    *this = ::std::move(from);
  }

  inline StartRemoteMessage& operator=(const StartRemoteMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline StartRemoteMessage& operator=(StartRemoteMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const StartRemoteMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const StartRemoteMessage* internal_default_instance() {
    return reinterpret_cast<const StartRemoteMessage*>(
               &_StartRemoteMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StartRemoteMessage& a, StartRemoteMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(StartRemoteMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StartRemoteMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StartRemoteMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StartRemoteMessage>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const StartRemoteMessage& from);
  void MergeFrom(const StartRemoteMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StartRemoteMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "flremoting.protocol.StartRemoteMessage";
  }
  protected:
  explicit StartRemoteMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserpathFieldNumber = 1,
    kPreviewhwndFieldNumber = 2,
  };
  // optional string userpath = 1;
  bool has_userpath() const;
  private:
  bool _internal_has_userpath() const;
  public:
  void clear_userpath();
  const std::string& userpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_userpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_userpath();
  PROTOBUF_NODISCARD std::string* release_userpath();
  void set_allocated_userpath(std::string* userpath);
  private:
  const std::string& _internal_userpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_userpath(const std::string& value);
  std::string* _internal_mutable_userpath();
  public:

  // optional uint32 previewhwnd = 2;
  bool has_previewhwnd() const;
  private:
  bool _internal_has_previewhwnd() const;
  public:
  void clear_previewhwnd();
  uint32_t previewhwnd() const;
  void set_previewhwnd(uint32_t value);
  private:
  uint32_t _internal_previewhwnd() const;
  void _internal_set_previewhwnd(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:flremoting.protocol.StartRemoteMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr userpath_;
  uint32_t previewhwnd_;
  friend struct ::TableStruct_flconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StartRemoteMessage

// optional string userpath = 1;
inline bool StartRemoteMessage::_internal_has_userpath() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool StartRemoteMessage::has_userpath() const {
  return _internal_has_userpath();
}
inline void StartRemoteMessage::clear_userpath() {
  userpath_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& StartRemoteMessage::userpath() const {
  // @@protoc_insertion_point(field_get:flremoting.protocol.StartRemoteMessage.userpath)
  return _internal_userpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StartRemoteMessage::set_userpath(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 userpath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:flremoting.protocol.StartRemoteMessage.userpath)
}
inline std::string* StartRemoteMessage::mutable_userpath() {
  std::string* _s = _internal_mutable_userpath();
  // @@protoc_insertion_point(field_mutable:flremoting.protocol.StartRemoteMessage.userpath)
  return _s;
}
inline const std::string& StartRemoteMessage::_internal_userpath() const {
  return userpath_.Get();
}
inline void StartRemoteMessage::_internal_set_userpath(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  userpath_.Set(value, GetArenaForAllocation());
}
inline std::string* StartRemoteMessage::_internal_mutable_userpath() {
  _has_bits_[0] |= 0x00000001u;
  return userpath_.Mutable(GetArenaForAllocation());
}
inline std::string* StartRemoteMessage::release_userpath() {
  // @@protoc_insertion_point(field_release:flremoting.protocol.StartRemoteMessage.userpath)
  if (!_internal_has_userpath()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = userpath_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (userpath_.IsDefault()) {
    userpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void StartRemoteMessage::set_allocated_userpath(std::string* userpath) {
  if (userpath != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  userpath_.SetAllocated(userpath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (userpath_.IsDefault()) {
    userpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:flremoting.protocol.StartRemoteMessage.userpath)
}

// optional uint32 previewhwnd = 2;
inline bool StartRemoteMessage::_internal_has_previewhwnd() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool StartRemoteMessage::has_previewhwnd() const {
  return _internal_has_previewhwnd();
}
inline void StartRemoteMessage::clear_previewhwnd() {
  previewhwnd_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline uint32_t StartRemoteMessage::_internal_previewhwnd() const {
  return previewhwnd_;
}
inline uint32_t StartRemoteMessage::previewhwnd() const {
  // @@protoc_insertion_point(field_get:flremoting.protocol.StartRemoteMessage.previewhwnd)
  return _internal_previewhwnd();
}
inline void StartRemoteMessage::_internal_set_previewhwnd(uint32_t value) {
  _has_bits_[0] |= 0x00000002u;
  previewhwnd_ = value;
}
inline void StartRemoteMessage::set_previewhwnd(uint32_t value) {
  _internal_set_previewhwnd(value);
  // @@protoc_insertion_point(field_set:flremoting.protocol.StartRemoteMessage.previewhwnd)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace flremoting

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_flconfig_2eproto
