// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flphonecasting.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_flphonecasting_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_flphonecasting_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_flphonecasting_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_flphonecasting_2eproto {
  static const uint32_t offsets[];
};
namespace flremoting {
namespace protocol {
class PhoneCastingMessage;
struct PhoneCastingMessageDefaultTypeInternal;
extern PhoneCastingMessageDefaultTypeInternal _PhoneCastingMessage_default_instance_;
}  // namespace protocol
}  // namespace flremoting
PROTOBUF_NAMESPACE_OPEN
template<> ::flremoting::protocol::PhoneCastingMessage* Arena::CreateMaybeMessage<::flremoting::protocol::PhoneCastingMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace flremoting {
namespace protocol {

// ===================================================================

class PhoneCastingMessage final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:flremoting.protocol.PhoneCastingMessage) */ {
 public:
  inline PhoneCastingMessage() : PhoneCastingMessage(nullptr) {}
  ~PhoneCastingMessage() override;
  explicit PROTOBUF_CONSTEXPR PhoneCastingMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PhoneCastingMessage(const PhoneCastingMessage& from);
  PhoneCastingMessage(PhoneCastingMessage&& from) noexcept
    : PhoneCastingMessage() {
    *this = ::std::move(from);
  }

  inline PhoneCastingMessage& operator=(const PhoneCastingMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline PhoneCastingMessage& operator=(PhoneCastingMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const PhoneCastingMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const PhoneCastingMessage* internal_default_instance() {
    return reinterpret_cast<const PhoneCastingMessage*>(
               &_PhoneCastingMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PhoneCastingMessage& a, PhoneCastingMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(PhoneCastingMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PhoneCastingMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PhoneCastingMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PhoneCastingMessage>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const PhoneCastingMessage& from);
  void MergeFrom(const PhoneCastingMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PhoneCastingMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "flremoting.protocol.PhoneCastingMessage";
  }
  protected:
  explicit PhoneCastingMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 3,
    kStatusFieldNumber = 1,
    kMethodFieldNumber = 2,
    kPortFieldNumber = 4,
  };
  // optional string ip = 3;
  bool has_ip() const;
  private:
  bool _internal_has_ip() const;
  public:
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // optional uint32 status = 1;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  uint32_t status() const;
  void set_status(uint32_t value);
  private:
  uint32_t _internal_status() const;
  void _internal_set_status(uint32_t value);
  public:

  // optional int32 method = 2;
  bool has_method() const;
  private:
  bool _internal_has_method() const;
  public:
  void clear_method();
  int32_t method() const;
  void set_method(int32_t value);
  private:
  int32_t _internal_method() const;
  void _internal_set_method(int32_t value);
  public:

  // optional uint32 port = 4;
  bool has_port() const;
  private:
  bool _internal_has_port() const;
  public:
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:flremoting.protocol.PhoneCastingMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
  uint32_t status_;
  int32_t method_;
  uint32_t port_;
  friend struct ::TableStruct_flphonecasting_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PhoneCastingMessage

// optional uint32 status = 1;
inline bool PhoneCastingMessage::_internal_has_status() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PhoneCastingMessage::has_status() const {
  return _internal_has_status();
}
inline void PhoneCastingMessage::clear_status() {
  status_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline uint32_t PhoneCastingMessage::_internal_status() const {
  return status_;
}
inline uint32_t PhoneCastingMessage::status() const {
  // @@protoc_insertion_point(field_get:flremoting.protocol.PhoneCastingMessage.status)
  return _internal_status();
}
inline void PhoneCastingMessage::_internal_set_status(uint32_t value) {
  _has_bits_[0] |= 0x00000002u;
  status_ = value;
}
inline void PhoneCastingMessage::set_status(uint32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:flremoting.protocol.PhoneCastingMessage.status)
}

// optional int32 method = 2;
inline bool PhoneCastingMessage::_internal_has_method() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool PhoneCastingMessage::has_method() const {
  return _internal_has_method();
}
inline void PhoneCastingMessage::clear_method() {
  method_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline int32_t PhoneCastingMessage::_internal_method() const {
  return method_;
}
inline int32_t PhoneCastingMessage::method() const {
  // @@protoc_insertion_point(field_get:flremoting.protocol.PhoneCastingMessage.method)
  return _internal_method();
}
inline void PhoneCastingMessage::_internal_set_method(int32_t value) {
  _has_bits_[0] |= 0x00000004u;
  method_ = value;
}
inline void PhoneCastingMessage::set_method(int32_t value) {
  _internal_set_method(value);
  // @@protoc_insertion_point(field_set:flremoting.protocol.PhoneCastingMessage.method)
}

// optional string ip = 3;
inline bool PhoneCastingMessage::_internal_has_ip() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PhoneCastingMessage::has_ip() const {
  return _internal_has_ip();
}
inline void PhoneCastingMessage::clear_ip() {
  ip_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PhoneCastingMessage::ip() const {
  // @@protoc_insertion_point(field_get:flremoting.protocol.PhoneCastingMessage.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PhoneCastingMessage::set_ip(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:flremoting.protocol.PhoneCastingMessage.ip)
}
inline std::string* PhoneCastingMessage::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:flremoting.protocol.PhoneCastingMessage.ip)
  return _s;
}
inline const std::string& PhoneCastingMessage::_internal_ip() const {
  return ip_.Get();
}
inline void PhoneCastingMessage::_internal_set_ip(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  ip_.Set(value, GetArenaForAllocation());
}
inline std::string* PhoneCastingMessage::_internal_mutable_ip() {
  _has_bits_[0] |= 0x00000001u;
  return ip_.Mutable(GetArenaForAllocation());
}
inline std::string* PhoneCastingMessage::release_ip() {
  // @@protoc_insertion_point(field_release:flremoting.protocol.PhoneCastingMessage.ip)
  if (!_internal_has_ip()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = ip_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (ip_.IsDefault()) {
    ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void PhoneCastingMessage::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  ip_.SetAllocated(ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (ip_.IsDefault()) {
    ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:flremoting.protocol.PhoneCastingMessage.ip)
}

// optional uint32 port = 4;
inline bool PhoneCastingMessage::_internal_has_port() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool PhoneCastingMessage::has_port() const {
  return _internal_has_port();
}
inline void PhoneCastingMessage::clear_port() {
  port_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline uint32_t PhoneCastingMessage::_internal_port() const {
  return port_;
}
inline uint32_t PhoneCastingMessage::port() const {
  // @@protoc_insertion_point(field_get:flremoting.protocol.PhoneCastingMessage.port)
  return _internal_port();
}
inline void PhoneCastingMessage::_internal_set_port(uint32_t value) {
  _has_bits_[0] |= 0x00000008u;
  port_ = value;
}
inline void PhoneCastingMessage::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:flremoting.protocol.PhoneCastingMessage.port)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace flremoting

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_flphonecasting_2eproto
